# Generated by Django 4.2.13 on 2026-04-06 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="candidate",
            name="unique_candidate_per_election",
        ),
    ]
